### ISSUE TITLE
Ballot#5 Alexander MENSE, HL7 Austria | From: References to smarthealthit.org | Replace all references to smarthealthit.org with a HL7 FHIR URL

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#10]
### Ballot Weight
NEG Correction

### Where
:: all

### What
Alexander MENSE, HL7 Austria
From: References to smarthealthit.org
Comment: Replace all references to smarthealthit.org with a HL7 FHIR URL

### Josh's Triage Notes
Merge with theme: "Extension URL Space"

### Disposition
See Theme: "Extension URL Space"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by isaacvetter** [comment]
Note that this issue/comment is a duplicate of #63
