### ISSUE TITLE
Ballot#97 Jason Walonoski, MITRE, on behalf of Dylan Mahalingam, Mahalingam, Dylan <kmahalingam@mitre.org> | From: The following capabilities conve...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#102]
### Ballot Weight
A-T

### Where
Specific Capabilities (by category) :: smart-app-launch/conformance/

### What
Jason Walonoski, MITRE, on behalf of Dylan Mahalingam, Mahalingam, Dylan <kmahalingam@mitre.org>
From: The following capabilities convey that a SMART on FHIR server is capable of provding basic context to an app at launch time.
To: The following capabilities convey that a SMART on FHIR server is capable of providing basic context to an app at launch time.
Comment: Correction to spelling of "providing."
Summary: Launch context subsection has spelling typo.

### Josh's Triage Notes
Disposition: Persuasive

We agree.

### Disposition
Disposition: Persuasive

We agree.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied
