### ISSUE TITLE
Ballot#106 John Moehrke, By Light Professional IT Services | From: App runs on a trusted server | App has server-side business logic (e.g. using PH...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#111]
### Ballot Weight
NEG

### Where
Support for âpublicâ and âconfidentialâ apps

### What
John Moehrke, By Light Professional IT Services
From: App runs on a trusted server
App has server-side business logic (e.g. using PHP, Python, Ruby, .NET, etc.)
To: App runs on a trusted platform

Comment: Better to differentiate that the application is running in trusted platform. This is not always a server, for example a fully enclosed hardware/software device.  The location of business logic is not helpful, and will only distract from the important point.

### Josh's Triage Notes
Merge with theme: "Where confidential apps can run"

### Disposition
See disposition for theme: "Where confidential apps can run"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
See #1 for proposed disposition
