### ISSUE TITLE
Ballot#113 John Moehrke, By Light Professional IT Services | Why does this specification differentiate between these 2 kinds? This section should a...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#117]
### Ballot Weight
A-S

### Where
Support for âpublicâ and âconfidentialâ apps :: /

### What
John Moehrke, By Light Professional IT Services
Comment: Why does this specification differentiate between these 2 kinds? This section should at least mention or reference what the difference means

### Josh's Triage Notes
Merge with theme "Where confidential apps can run"

### Disposition
See disposition for theme: "Where confidential apps can run"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
See #1 for proposed disposition
