### ISSUE TITLE
Ballot#115 John Moehrke, By Light Professional IT Services | From: An app should NEVER treat any inputs it receives as executable code. | What does...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#119]
### Ballot Weight
A-C

### Where
SMART authorization and resource retrieval :: /

### What
John Moehrke, By Light Professional IT Services
From: An app should NEVER treat any inputs it receives as executable code.
Comment: What does 'treat' mean in this context? I presume you are discouraging any element to carry script or otherwise executable. It is just not clear what 'treat' means. Thus it is either easy to achieve this, or impossible to achieve this.

### Josh's Triage Notes
We are trying to say "never execute your inputs as code". What would be a clearer way?

### Disposition
Disposition: persusasive with mod

We are trying to say ""never execute your inputs as code"".  We can re-words to eliminate ""treat"" from the sentence.
Eric Haas / Debbie Bucci
7-0-0

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
applied
