### ISSUE TITLE
Ballot#130 John Moehrke, By Light Professional IT Services | Need a section for SMART "Security & Privacy Considerations". Describe: Expected use, ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#132]
### Ballot Weight
NEG

### Where
Security Considerations

### What
John Moehrke, By Light Professional IT Services
Comment: Need a section for SMART "Security & Privacy Considerations". Describe: Expected use, and environments not addressed; Responsibilities of the App developer, SMART server developer, Organization deploying App, and Organization deploying SMART server. Specifically around "Threat Model", designed in mitigations for those threats, and residual risk. Emphaisis on residual risk that would need to be addressed by Policy, Procedures, and Operational controls. Controls like Audit Log analysis and reaction.  (leverage the OAuth threat model and security considerations, mostly just addressing the SMART implementation guide).

### Josh's Triage Notes
Many relevant details are included in the authorization specification, including threat model. What specific security and privacy considerations would it be helpful to add? We have included the resutls of the analysis we performed; is the proposal to perform another analysis?

### Disposition
Not persuasive with mod

We should defer the creation of large new sections to a future release of the specification, except in areas that are clearly preventing implementation progress. This might be a set of considerations that the Security WG might take on.

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
Are there any publication changes here?  for example, a future scope section?
