### ISSUE TITLE
Ballot#136 John Moehrke, By Light Professional IT Services | From: Other HIPAA-mandated â¦ | HIPAA is a USA centric federal regulation. It is best...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#137]
### Ballot Weight
NEG

### Where
Profile audience and scope :: /

### What
John Moehrke, By Light Professional IT Services
From: Other HIPAA-mandated â¦
Comment: HIPAA is a USA centric federal regulation. It is best to not mention, as the Privacy and Security concerns are international.

### Josh's Triage Notes
We can remove references to HIPAA, though in practice it is useful context for many implementers.

### Disposition
Persuasive with mod

Immediate step: update the language to clarify HIPAA is an example "Other security mechanisms, such as those mandated by HIPAA in the US (end-user authentication, ... ) are outside the scope of this profile."

Future step: evaluate in the context of other regions and countries (e.g. GDRP  in Europe)

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
applied
