### ISSUE TITLE
Ballot#142 John Moehrke, By Light Professional IT Services | Recommend re-organize with separate pages for scopes vs launch context

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#139]
### Ballot Weight
A-S

### Where
:: /scopes-and-launch-context/

### What
John Moehrke, By Light Professional IT Services
Comment: Recommend re-organize with separate pages for scopes vs launch context

### Josh's Triage Notes
This is tricky; there is in several cases a clear correspondance between scopes and the launch context that they request/provide.

### Disposition
Disposition: Persuasive

Separate content into a ""Scopes"" and a ""Launch Context"" -- easier to link to and explain.

### Vote Details
Pro-Con-Abstain: 9-0-0
Date: 2017-11-30

**Comment by Healthedata1** [comment]
We tried this and made it less readable.  Will keep as a single section/page
