### ISSUE TITLE
Ballot#148 John Moehrke, By Light Professional IT Services | From: Request a refresh_token that can be used to obtain a new access token to replace...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#145]
### Ballot Weight
A-S

### Where
:: /scopes-and-launch-context/

### What
John Moehrke, By Light Professional IT Services
From: Request a refresh_token that can be used to obtain a new access token to replace an expired one, even after the end-user no long is online after the access token rexpires
To: Request a refresh_token that can be used to obtain a new access token to replace an expired one, even after the end-user is no longer interactively engaged.

### Josh's Triage Notes
Disposition: Persuasive

### Disposition
Disposition: Persuasive

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
addressed by #243
