### ISSUE TITLE
Ballot#151 John Moehrke, By Light Professional IT Services | How is patient scope to be treated in cases with _include or _revinclude (or etc) that...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#148]
### Ballot Weight
A-S

### Where
:: /scopes-and-launch-context/

### What
John Moehrke, By Light Professional IT Services
Comment: How is patient scope to be treated in cases with _include or _revinclude (or etc) that as for resources related to those identified with the query parameters?

### Josh's Triage Notes
Disposition: Considered - Question Answered

The scope should be interpreted by the EHR; decisions about which resources to include should be made on the basis of the entire set of scopes associated wtih the access token used for a request.

### Disposition
Disposition: Considered - Question Answered

The scope should be interpreted by the EHR; decisions about which resources to include should be made on the basis of the entire set of scopes associated wtih the access token used for a request.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
do we want to add this to the specification
