### ISSUE TITLE
Ballot#153 Joshua Mandel, Boston Children's Hospital | @https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/136 | Review the mechanism ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#150]
### Ballot Weight
A-S

### Where
:: https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/136

### What
Joshua Mandel, Boston Children's Hospital
@https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/136
Comment: Review the mechanism for passing conformance details and decide between the proposed extension-based mechanism and a standalone JSON discovery document.

### Josh's Triage Notes
Consider this change (there are are trade-offs)

### Disposition
Follow the OIDC protocol. A client can go from knowing the Issuer

--> ${Issuer}/.well-known/openid-configuration
--> Parse JSON and extract  "jwks_uri" property
--> Dereference "jwks_uri" to obtain the actual key set.

Note that information about the token URI, authorize URI, registration URI, and OIDC Issuer URI are available in the ${FHIR Base}/.well-known/smart-configuration as well as ${Issuer}/.well-known/openid-configuration .

### Vote Details
Pro-Con-Abstain: 10-0-2
Date: 2017-09-14

**Comment by Healthedata1** [comment]
see #249
