### ISSUE TITLE
Ballot#156 Joshua Mandel, Boston Children's Hospital | @https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/135 | From: Some apps need ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#153]
### Ballot Weight
NEG

### Where
:: http://www.hl7.org/fhir/smart-app-launch/scopes-and-launch-context/

### What
Joshua Mandel, Boston Children's Hospital
@https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/135
From: Some apps need to authenticate the clinical end-user. This can be accomplished by requesting a pair of OpenID Connect scopes: openid and profile.
Comment: The specification should explain what features of OIDC must be supported. Is it the entire Core Profile? Some minimal subset?

### Josh's Triage Notes
Merge with theme: "Clarify OIDC"

### Disposition
See disposition from theme: "Clarify OIDC"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
See #249
