### ISSUE TITLE
Ballot#160 Kanwarpreet Sethi, Lantana Consulting Group, on behalf of Sean McIlvenna, sean.mcilvenna@lantanagroup.com | It would be helpful if the I...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#157]
### Ballot Weight
A-S

### What
Kanwarpreet Sethi, Lantana Consulting Group, on behalf of Sean McIlvenna, sean.mcilvenna@lantanagroup.com
Comment: It would be helpful if the IG had a section that described (at a high-level, at least) the differences between standard OAuth2 and what this IG suggests. Much of this describes typical OAuth2 workflow, and it is not clear where the "SMART app launch" adds to the workflow.
Summary: Create section describing differences from typical OAuth2 workflow

### Josh's Triage Notes
We should consider a high-level overview in a subsequent publication.

### Disposition
Given lack of consistency in typical OAuth 2.0 workflows, there doesn't appear to be a good value proposition for this change.

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
resolved - no change
