### ISSUE TITLE
Ballot#161 Kanwarpreet Sethi, Lantana Consulting Group, on behalf of Arvind Jaganathan, arvind.jaganathan@lantanagroup.com | I feel like the inform...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#158]
### Ballot Weight
A-S

### Where
:: http://www.hl7.org/fhir/smart-app-launch/conformance/core-set/

### What
Kanwarpreet Sethi, Lantana Consulting Group, on behalf of Arvind Jaganathan, arvind.jaganathan@lantanagroup.com
Comment: I feel like the information stored on the "Conformance: Core Set" page would be more understandable if it was stored on the "Declaring Conformance" page.  It seems odd to me that the information is split across multiple pages when they directly refer to the same material.

### Josh's Triage Notes
Incorporate the  "Core Set" details into the "Declaring Conformance" page.

### Disposition
There's value in having shorter pages.

Organize into 3 pages?
 * Lists Capabilities
 * Lists Capability Sets (include example conformance)
 * Explains the syntax for declaring conformance

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
Partially applied.   Arranging Conformance + Core Set (161, 162) -  need to update the contents.

**Comment by Healthedata1** [comment]
what else needs to be applied here?

**Comment by Healthedata1** [comment]
#159

**Comment by Healthedata1** [comment]
see #159
