### ISSUE TITLE
Ballot#162 Kanwarpreet Sethi, Lantana Consulting Group, on behalf of Arvind Jaganathan, arvind.jaganathan@lantanagroup.com | Same as above.  The in...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#159]
### Ballot Weight
A-S

### Where
:: http://www.hl7.org/fhir/smart-app-launch/capability-statement/

### What
Kanwarpreet Sethi, Lantana Consulting Group, on behalf of Arvind Jaganathan, arvind.jaganathan@lantanagroup.com
Comment: Same as above.  The information stored in the "Capability Statement" page would be more understandable placed within the "Declaring Conformance" page.  I personally don't feel like the information within this page makes sense without the background information that accompanies it on the "Declaring Conformance" page.

### Josh's Triage Notes
Incorporate the  "Core Set" details into the "Declaring Conformance" page.

### Disposition
There's value in having shorter pages.

Organize into 3 pages?
 * Lists Capabilities
 * Lists Capability Sets (include example conformance)
 * Explains the syntax for declaring conformance

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
partially applied Arranging Conformance + Core Set (161, 162)

**Comment by Healthedata1** [comment]
I think can close this one...

**Comment by Healthedata1** [comment]
update the core language to make clear 4 relevant sets for specific use cases and a define a list of all capabilities.
