### ISSUE TITLE
Ballot#167 Keith W. Boone, GE Healthcare | From: The app MUST use an unpredictable value for the state parameter with at least 128 bits of entropy ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#164]
### Ballot Weight
NEG Enhancement

### Where
SMART authorization and resource retrieval :: http://www.hl7.org/fhir/smart-app-launch/

### What
Keith W. Boone, GE Healthcare
From: The app MUST use an unpredictable value for the state parameter with at least 128 bits of entropy
To: The app MUST use an unpredictable value for the state parameter with at least 128 bits of entropy (NOTE: A UUID contains at most 124 bits of entropy).
Comment: Many will use UUIDs for this, thinking they meet the criteria.  Adding the note makes it clear that a random UUID is not sufficient.  NOTE: If a random UUID is sufficient, change the number of random bits necessary in the statement.

### Josh's Triage Notes
Good point. I think 122 bits should be sufficient for state parameter, so random UUIDs should work.

### Disposition
Persuasive.

We agree that random UUIDs are appropriate, and 122 bits of entropy are sufficient. We will update the specification to indicate this.

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
applied

**Comment by Healthedata1** [comment]
committed in #202

**Comment by jmandel** [comment]
We should words this differently: "122 bits of entropy (e.g., a properly configured random uuid is suitable)."
