### ISSUE TITLE
Ballot#178 Keith W. Boone, GE Healthcare | SMART on FHIR must work with both DSTU2 and STU3.  The specification must be clear on how metadata endpo...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#175]
### Ballot Weight
NEG Clarification

### Where
Publishing Additional Conformance Details :: http://www.hl7.org/fhir/smart-app-launch/capability-statement/

### What
Keith W. Boone, GE Healthcare
Comment: SMART on FHIR must work with both DSTU2 and STU3.  The specification must be clear on how metadata endpoint must work in DSTU2 as well as the CapabilityStatement in STU3.

### Josh's Triage Notes
This specification has been focused on STU3. Would it help to add a note to the effect of "For DSTU2, the resource is called 'Conformance'" ?

### Disposition
Persuasive. 

We covered this last time but forgot to include this comment in our vote. Refer to previous disposition on item #71:

> We should include text explaining "When using this spec with FHIR DSTU2, the CapabilityStatement is instead called ConformanceStatement."

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
partially applied using the "publish-box" to define which version of FHIR to which the specification applies.
added Conformance note,
anything else?
