### ISSUE TITLE
Ballot#180 Kensaku Kawamoto, MD, PhD, MHS, University of Utah | From: Other HIPAA-mandated security mechanisms, such as end-user authentication, se...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#177]
### Ballot Weight
NEG

### Where
:: http://www.hl7.org/fhir/smart-app-launch/

### What
Kensaku Kawamoto, MD, PhD, MHS, University of Utah
From: Other HIPAA-mandated security mechanisms, such as end-user authentication, session time-out, security auditing, and accounting of disclosures, are outside the scope of this profile.
Comment: Because a key part of SMART is about security, and users of SMART will need to know how to ensure HIPAA compliance (at least in the U.S.), I think there should be more of a discussion of what a healthcare system/implementer needs to do to ensure regulatory compliance when using SMART, esp. with an external host.
Summary: HIPAA and security regulations

### Josh's Triage Notes
Note this conflicts with another comment that we should omit mention of US-specific HIPAA.

### Disposition
Persuasive with mod

Immediate step: update the language to clarify HIPAA is an example "Other security mechanisms, such as those mandated by HIPAA in the US (end-user authentication, ... ) are outside the scope of this profile."

Future step: evaluate in the context of other regions and countries (e.g. GDRP  in Europe)

### Vote Details
Pro-Con-Abstain: 7-0-0
Date: 2017-12-14

**Comment by Healthedata1** [comment]
applied

**Comment by Healthedata1** [comment]
#202
