### ISSUE TITLE
Ballot#188 Kensaku Kawamoto, MD, PhD, MHS, University of Utah | From: String value with a relative resource link, describing some specific resource...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#183]
### Ballot Weight
A-T

### Where
:: http://www.hl7.org/fhir/smart-app-launch/scopes-and-launch-context/

### What
Kensaku Kawamoto, MD, PhD, MHS, University of Utah
From: String value with a relative resource link, describing some specific resource context for the (in this case, a particular medication prescription). This is a generic mechanism to communicate to an app that a particular resource is âof interestâ at launch time.
Comment: Seems a word is missing before parentheses
Summary: Typo

### Josh's Triage Notes
Disposition: Persuasive with mod.

We will add the word "launch". We also note that we have removed the "resource" context param altogether.

### Disposition
Disposition: Persuasive with mod.

We will add the word "launch". We also note that we have removed the "resource" context param altogether.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied
