### ISSUE TITLE
Ballot#204 Nell Lapres, Epic, on behalf of Isaac Vetter, isaac@epic.com | In the case where the OIDC JWT header has a alg value of "none", the app ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#197]
### Ballot Weight
NEG

### Where
3. App exchanges authorization code for access token :: http://www.hl7.org/fhir/smart-app-launch/#3-app-exchanges-authorization-code-for-access-token

### What
Nell Lapres, Epic, on behalf of Isaac Vetter, isaac@epic.com
Comment: In the case where the OIDC JWT header has a alg value of "none", the app must reject any claims where the issuer is different from the url of the authorization server. This is discussed here: https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/135
Summary: OIDC JWS "alg" of "none", issuer and AS must be the same

### Josh's Triage Notes
Theme: "Issuer Discovery"

We should talk through the link from (fhir server --> public keys), (fhir server -?-> issuer), (fhir server --> authorization server), and (authorization server --> public keys)

### Disposition
See Theme: "Extension URL Space"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
not sure what the disposition for this on is ... since there is no real proposal
