### ISSUE TITLE
Ballot#205 Nell Lapres, Epic, on behalf of Clark Downum, clark@epic.com | From: Security assurance comes from being hosted within a trusted server ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#198]
### Ballot Weight
A-S

### Where
Support for âpublicâ and âconfidentialâ apps :: http://www.hl7.org/fhir/smart-app-launch/index.html

### What
Nell Lapres, Epic, on behalf of Clark Downum, clark@epic.com
From: Security assurance comes from being hosted within a trusted server environment.
To: For statically distributed keys, security assurance comes from being hosted within a trusted server environment.
Comment: security does not necessarily come from running in a trusted environment and that may give an incorrect (and unfair) impression of an app that is on a user device but is secure.  Iâd say that a statically distributed key needs an app to be run in a trusted environment but an app that has a key per instance can be confidential even if itâs on a phone.  See OAuth 2.0 for Native Apps (https://tools.ietf.org/html/draft-ietf-oauth-native-apps-12)
Summary: Minor wording change: security doesn't necessarily come from running in a trusted environment

### Josh's Triage Notes
Merge with theme: "Where confidential apps can run"

### Disposition
See disposition for theme: "Where confidential apps can run"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
See #1 for proposed disposition
