### ISSUE TITLE
Ballot#207 Nell Lapres, Epic, on behalf of Clark Downum, clark@epic.com | From: The user should be given information regarding the client requestin...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#200]
### Ballot Weight
A-S

### Where
2. EHR evaluates authorization request, asking for end-user input :: http://www.hl7.org/fhir/smart-app-launch/index.html

### What
Nell Lapres, Epic, on behalf of Clark Downum, clark@epic.com
From: The user should be given information regarding the client requesting the access, the request, the scope, and the time access is needed.
To: The user should be given information regarding the client requesting the access, the request, and the scopes being requested.
Comment: The amount of time access is being asked for should not be expected to be displayed to the user.  Iâm not aware of any other OAuth2 solution that does this.
Summary: Shouldn't have to tell the user about expires_in.

### Josh's Triage Notes
Approval for access to healthcare data often comes with time bounds; at the level of high-level UI guidance, I think it's appropriate to provide this suggestion. It's not binding.

### Disposition
Disposition: Not Persuasive

Approval for access to healthcare data often comes with time bounds; at the level of high-level UI guidance, It's appropriate to provide this suggestion. It's not binding.

Motion: Eric Haas, Second: Jeff Danford
9-0-0

### Vote Details
Pro-Con-Abstain: 9-0-0
Date: 2017-11-30

**Comment by Healthedata1** [comment]
completed - no change required
