### ISSUE TITLE
`launch` parameter vs OpenID's `login_hint`

### ISSUE THREAD

**Issue by hauntingEcho** [HL7/smart-app-launch#289]
I may be misreading the purpose of the `launch` parameter in [the EHR-initiated launch sequence](http://hl7.org/fhir/smart-app-launch/#ehr-launch-sequence), but it seems like this behavior is already covered by the `login_hint` parameter in OpenID Connect's [third-party initiated login flow](https://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin).

`launch` is an identifier for a specific login flow.  Since the login flow can be identified, I'd argue it implies the already-authenticated user - meeting OpenID Connect's login_hint definition: `Hint to the Authorization Server about the login identifier the End-User might use to log in.`.

Given this, what is the driver for specifying an additional parameter rather than using `launch`'s current definition as a restriction on the type of login_hint to be sent?  Using OpenID's existing parameter would simplify integration with the existing OpenID Connect ecosystem.

**Comment by jmandel** [comment]
This parameter captures the specific semantics of "launch context is available to be shared with the app", rather than a hint about the identity of the end user.
