### ISSUE TITLE
Improve SMART's scope language

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#296]
Proposed enhancements include scopes to enable:

* Access at the category level (e.g., all Vital Sign Observations rather than all Observation)
* Access to data at a certain sensitivity level (e.g., by security tag) or specific purposes
* Access to specific Operations within the FHIR operations framework

Some discussion at:
* https://healthcaresecprivacy.blogspot.com/2017/05/fhir-oauth-scope-proposal-using-fhir.html
* https://medium.com/@jafarim/using-json-to-model-complex-oauth-scopes-fa8a054b2a28;

**Comment by joostreuzel** [comment]
Please include allowance to send specific types of FHIR messages (eg. as used in certain IHE profiles like IHE-PMIR)

**Comment by jmandel** [comment]
Closing this issue as out-of-date; we're taken this on in the Argonaut 2020 project.

**Comment by daniel-thomson** [comment]
@jmandel  Did this go anywhere? 

We're using the SMART scopes syntax for some of our implementations, and alongside those APIs we're starting to do some messaging (using the $process-message). We need a scope for accepting messages - initially we'll probably go with system/MessageHeader.c - but can see the need for a more expressive syntax for FHIR operations (including messaging).

**Comment by jmandel** [comment]
We have not come up with better rules around operations. If you can express the permissions for your operation in terms of CRUDS, then the approach you are suggesting here sounds really good.

Operations that invoke other kinds of behavior besides just CRUDS require some more nuance. For these, I am recommending that you just use the canonical URL of the operation if you don't care about the parameters. If you need to bind certain parameters to fixed values, I would try to attach them as query parameters. If the parameters you need to bind only work in the body, I think we are going to be stuck.

**Comment by daniel-thomson** [comment]
Thanks, that's helpful.
