### ISSUE TITLE
Wrong scope in standalone launch sequence diagram

### ISSUE THREAD

**Issue by michelemottini** [HL7/smart-app-launch#316]
The diagram at http://hl7.org/fhir/smart-app-launch/index.html#standalone-launch-sequence: 

![image](https://user-images.githubusercontent.com/1046280/96729754-80f33c80-1383-11eb-933f-3d7eda9cdf66.png)

indicates a `scope=launch` that does not really apply to standalone launch - it should `launch/patient` or an access scope (or a combination)

**Comment by jmandel** [comment]
We defined the `launch` scope at http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context/index.html#quick-start -- it's how an app tells the EHR "I want to request access to launch context information"

**Comment by jmandel** [comment]
after discussion on zulip: scope would be appropriate in the EHR launch sequence but it should not be here in the standalone launch sequence.

**Comment by jmandel** [comment]
This diagram has been updated
