### ISSUE TITLE
Make Authorize POST an Optional Capability

### ISSUE THREAD

**Issue by madaster97** [HL7/smart-app-launch#331]
# Optional Support for Authorize POST
The `authorize-post` capability should be **optional** for an authorization server to support.
 
The `authorize-post` capability is intended to counter the growth in string length of an app's scopes string. This is particularly needed for FHIR servers with support for significant numbers of resources, and for authorization servers that differentiate between scopes defined at registration versus requested at authorization. In many production scenarios, the string length of an app's scopes is not problematic.
 
Servers should be able to implement (and broadcast) the authorize-post capability as needed. We should consider making POST based authorization optional for servers, and separating out this capability between EHR and Standalone launch scenarios:

- `authorize-post-ehr`
- `authorize-post-standalone`

**Comment by jmandel** [comment]
Cross-posting [with Zulip](https://chat.fhir.org/#narrow/stream/179170-smart/topic/SMARTv2.20Connectathon.2C.20Jan.202021.20--.20discovered.20isseus/near/222916917)...

Re: post-based authorization in particular, can you say more about why `authorize-post` would be better left as optional? It was the solution to our biggest problem involved in introducing granular scopes (unboudned URL length), and it's also a [SHALL level requirement](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) in OpenID Connect Core.

**Comment by madaster97** [comment]
Authorize-Post does solve that problem, but my main point is that it should only be required IF that problem would actually occur otherwise. If apps aren't expected to use long scope strings against a server (couple scenarios in first comment) then it could be justified the server doesn't support it.

What implications does the OIDC "Shall" have here?

**Comment by jmandel** [comment]
The goal is to ensure consistent client behavior, which is easier when capabilities are consistently supported.

Re: OIDC "Shall," I think that'd apply "already" to servers that support the SMART SSO capability. (But at a minimum, the implication: this is a well-standardized and well-vetted concept rather than something we're "inventing" here.)

**Comment by madaster97** [comment]
I see what you mean with the existing OIDC requirement. Closing this one!
