### ISSUE TITLE
Smart Launch "aud" parameter 

### ISSUE THREAD

**Issue by rnairgd** [HL7/smart-app-launch#337]
The "aud" parameter in the SMART launch is not OIDC Compliant and not supported by many OAuth Providers . Even if the IDP can receive the variable ( e.g "aud"=https://simpledomain.com/fhir/patient/123434 ) as a part of Access Token Request  , The OAuth Authorization Servers are not in a position to validate such fine grained authorization request and understand one to many relationship between the user id and the patient id . In our instance , for example, we use the a common IDP used by the larger citizen population and we cannot put these nuanced rules in to the IDP.
Based on the OIDC best practices , it is the resource server's job to validate the "aud" from the JWT to ensure that token that is being presented is indeed issued to the Intendent audience . 
It is also worth noting that the adding such URI's in to the JWT in turn make it carry PII. I think this should be made an optional field .

**Comment by jmandel** [comment]
We have discussed this parameter extensively in HL7 FHIR Infrastructure workgroup. Note that

* `aud` parameter is passes to the IDP as a parameter to the authz endpoint, not as a JWT parameter
*  `aud` identifies an endpoint and not a patient.
