### ISSUE TITLE
Can we go further than resource types in clinical scope syntax?

### ISSUE THREAD

**Issue by MeriemMfi** [HL7/smart-app-launch#359]
For example, if we have multiple profiles for the Observation resource : weight and heart rate and we need to define specific scopes for each of these profiles. Is there a way to do it (using the profile canonical url or name)?

**Comment by jmandel** [comment]
The SMART 2.0 granular scope syntax provides a way to express these -- but it's unlikely that this functionality can be supported generally by real-world EHR systems. Pure FHIR servers have a better shot.
