### ISSUE TITLE
Transfer from Bulk IG Ballot

### ISSUE THREAD

**Issue by gotdan** [HL7/smart-app-launch#360]
Edits to current Backend Services page (applied in https://github.com/HL7/bulk-data/pull/114):
FHIR-32331
FHIR-32329
FHIR-32184
FHIR-32182
FHIR-32185
FHIR-32181
FHIR-32187
FHIR-32328

Ballot issues from Bulk that we need to review and ensure they are address in SMART App Launch:
- [ ] FHIR-32407
- [ ] FHIR-32338
- [ ] FHIR-32186
- [ ] FHIR-32183
- [ ] FHIR-32180
- [ ] FHIR-32134
- [ ] FHIR-32013

**Comment by jmandel** [comment]
Capturing these TODOs in https://jira.hl7.org/browse/FHIR-33073 and closing
