### ISSUE TITLE
SMART App Launch Framework Typos

### ISSUE THREAD

**Issue by vivekrckr** [HL7/smart-app-launch#369]
In the document SMART App Launch Framework, I found a minor typo:

- In section 7.1.6 (http://www.hl7.org/fhir/smart-app-launch/#step-5-later-app-uses-a-refresh-token-to-obtain-a-new-access-token)  > **JSON Object property name**  > `refresh_token`, 'previosu' should be replaced with 'previous'.

**Comment by jmandel** [comment]
Fixed, thank you!
