### ISSUE TITLE
SMART App Launch: Allow client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer for confidential app authorization flow

### ISSUE THREAD

**Issue by tstolker** [HL7/smart-app-launch#370]
Based on the fact that our solution uses the client credentials grant flow as guided under the SMART Backend Services: Authorization flow (see https://hl7.org/fhir/uv/bulkdata/authorization/index.html#obtaining-an-access-token) we feel that it would improve the SMART Appl Launch standard if to allow/suggest the use the client credentials (client_assertion_type =urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=...) instead of the basic authorization header when acquiring the token based on the authorization code.

**Comment by madaster97** [comment]
@tstolker - I think this is fixed now. Did you mean to ask for the "private_key_jwt" client authentication type? Here's the [spec section](http://www.hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html) and example [here](http://www.hl7.org/fhir/smart-app-launch/example-app-launch-asymmetric-auth.html#retrieve-access-token). The grant_type is still authorization_code/refresh_token, but you're adding the client_assertion and client_assertion_type parameters to authenticate those grants.

**Comment by tstolker** [comment]
Thanks, @madaster97 , this looks great!
