### ISSUE TITLE
Ballot#37 Grahame Grieve | From: but they canât âkeep a secret | inappropriate space after the ' - and throughout this document

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#41]
### Ballot Weight
A-T

### Where
Support for âpublicâ and âconfidentialâ apps :: /

### What
Grahame Grieve
From: but they canât âkeep a secret
Comment: inappropriate space after the ' - and throughout this document

### Josh's Triage Notes
Disposition: Persuasive 

We should make this tix.

### Disposition
Disposition: Persuasive 

We should make this tix.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied ( not issue using ig publisher framework )
