### ISSUE TITLE
Ballot#41 Grahame Grieve | From: For background, see the OAuth 2.0 Threat Model and Security Considerations | The document should differentiate bet...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#45]
### Ballot Weight
NEG Enhancement

### Where
SMART authorization and resource retrieval :: /

### What
Grahame Grieve
From: For background, see the OAuth 2.0 Threat Model and Security Considerations
Comment: The document should differentiate between internal and external references (as FHIR does)

### Josh's Triage Notes
Disposition: Persuasive 

We agree that we should put publication tools and templates in place to accomplish this.

### Disposition
Disposition: Persuasive 

We agree that we should put publication tools and templates in place to accomplish this.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
see #223
