### ISSUE TITLE
Ballot#49 Grahame Grieve | From: The EHR authorization server SHALL return a JSON structure | To: The EHR authorization server SHALL return a JSON ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#53]
### Ballot Weight
A-T

### Where
SMART authorization and resource retrieval :: /

### What
Grahame Grieve
From: The EHR authorization server SHALL return a JSON structure
To: The EHR authorization server SHALL return a JSON object

### Josh's Triage Notes
Disposition: Persuasive

We agree.

### Disposition
Disposition: Persuasive

We agree.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied
