### ISSUE TITLE
Ballot#52 Grahame Grieve | From: GET https://ehr/fhir/Patient/123 | Authorization: Bearer i8hweunweunweofiwweoijewiwe |  | { |   "resourceType": "P...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#56]
### Ballot Weight
A-T

### Where
SMART authorization and resource retrieval :: /

### What
Grahame Grieve
From: GET https://ehr/fhir/Patient/123
Authorization: Bearer i8hweunweunweofiwweoijewiwe

{
  "resourceType": "Patient",
  "birthTime": ...
}
Comment: this conflates request and response..

### Josh's Triage Notes
Disposition: Persuasive

We agree. This should be broken into a Request and a Response box as for the subsequent example.

### Disposition
Disposition: Persuasive

We agree. This should be broken into a Request and a Response box as for the subsequent example.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied
