### ISSUE TITLE
Ballot#53 Grahame Grieve | From: even after the end-user no long is online after | To: even after the end-user no longer is online after

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#57]
### Ballot Weight
A-T

### Where
SMART authorization and resource retrieval :: /

### What
Grahame Grieve
From: even after the end-user no long is online after
To: even after the end-user no longer is online after

### Josh's Triage Notes
Disposition: Persuasive

We agree.

### Disposition
Disposition: Persuasive

We agree.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied
