### ISSUE TITLE
Ballot#55 Grahame Grieve | From: authoriztion | To: authorization

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#59]
### Ballot Weight
A-T

### Where
Wildcard scopes :: /scopes-and-launch-context/

### What
Grahame Grieve
From: authoriztion
To: authorization

### Josh's Triage Notes
Disposition: Persuasive

We agree.

### Disposition
Disposition: Persuasive

We agree.

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied
