### ISSUE TITLE
Ballot#57 Grahame Grieve | From: Core SMART on FHIR Support that includes support for |  | both launch modes (EHR Launch + Standalone Launch) | How...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#61]
### Ballot Weight
NEG Clarification

### Where
SMART on FHIR Conformance :: /conformance/

### What
Grahame Grieve
From: Core SMART on FHIR Support that includes support for

both launch modes (EHR Launch + Standalone Launch)
Comment: How does it make sense to require the capability to do EHR Launch? What about when there's no facility to launch? Do we just require a meaningless claim?

### Josh's Triage Notes
Merge with theme: "Conformance Levels"

### Disposition
See disposition for theme "Conformance Levels"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
applied  Conformance Levels (57, 170-175, 194)
