### ISSUE TITLE
Ballot#59 Grahame Grieve | From: extensions | The URLs should all the changed to hl7 hosted fhir URLs, and definitions published.

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#63]
### Ballot Weight
NEG Correction

### Where
Publishing OAuth2 URLs :: /capability-statement/

### What
Grahame Grieve
From: extensions
Comment: The URLs should all the changed to hl7 hosted fhir URLs, and definitions published.

### Josh's Triage Notes
Theme: "Extension URL Space"
Note this proposes a breaking change for all current SMART implementations. I think this needs discussion.

### Disposition
* We do not want to make breaking changes to the spec
* We agree that any extensions should be properly defined and hosted as StructureDefinitions
* We want to move forward, over time, with a ".well-known/smart-configuration"
* Start by representing our current discovery details in both places (/metadata and .well-known/smart-configuration)
* The SMART capabilities (e.g. launch-standalone, etc) should only be represented in .well-known/smart-configuration
* We will begin with the proposal at https://gist.github.com/p2/9155e9324143e1d48370ad59b285e24c and review details, with a plan to add "issuer" and capabilities to the set of data that can be discovered
* We will consider the values in CapabilityStatement (/metadata) to be deprecated and they will be removed in a subsequent release. This will ensure that eventually we move away from smarthealthit.org-based extension URLs.

### Vote Details
Pro-Con-Abstain: 11-0-1
Date: 2017-09-14

**Comment by jmandel** [comment]
We want to make sure the `CapabilityStatement`-based approach is still working @Healthedata1

**Comment by isaacvetter** [comment]
Hi everybody, 

Is the guidance to developers to represent scopes as a uri of `http://smarthealthit.org/fhir/scopes/patient/*.read` inconsistent with this ballot comment?

The spec at smarthealthit, the balloted publication and the final publication all instruct developers to use a smarthealthit uri:
- http://docs.smarthealthit.org/authorization/scopes-and-launch-context/#appendix-uri-representation-of-scopes
- http://docs.smarthealthit.org/authorization/scopes-and-launch-context/#appendix-uri-representation-of-scopes
- http://build.fhir.org/ig/HL7/smart-app-launch/scopes-and-launch-context/index.html#appendix-uri-representation-of-scopes

The ballot vote was clear - preserve backwards compatibility and provide a path to move from smarthealthit uris. 

It clearly makes sense to leave scopes as uris of smarthealthit, but there's no current path to use hl7 fhir uris. 

Isaac

**Comment by Healthedata1** [comment]
Is the suggestion to have two base paths?

http://docs.smarthealthit.org/

and 

http://hl7.org/fhir/

**Comment by jmandel** [comment]
We agreed to preserve the SMART extension URLs, rather than moving to hl7.org extensions URLs, to preserved compatibility. Similarly, we're maintaining these scope URLs (but note that this is more of a system-internal detail; mostly nobody will be using the full URL representation of scopes over the wire).
