### ISSUE TITLE
Ballot#60 Grahame Grieve | From: Use the confidential app profile |  | when all of the following apply: |  | App runs on a trusted server | App has...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#64]
### Ballot Weight
NEG Correction

### Where
Support for âpublicâ and âconfidentialâ apps :: /

### What
Grahame Grieve
From: Use the confidential app profile

when all of the following apply:

App runs on a trusted server
App has server-side business logic (e.g. using PHP, Python, Ruby, .NET, etc.)
App is able to protect a client_secret
Use the public app profile

when all of the following apply:

App runs on an end-userâs device (e.g. HTML5/JS in-browser; native iOS, Windows, or Android)
App is unable to protect a client_secret
Comment: What if you are in a situation where not all of those apply in either direction? This should be clarified. More generally, this language should be clearly advisory, not normative (e.g  should not shall), or if normative is desired, it should be extremely clear, and the ramifications of the impact it makes should be carefully considered

### Josh's Triage Notes
Merge with theme: "Where confidential apps can run"

Agreed this should be advisory language. We should also consider explanations about how to proceed if neither condition is completely correct.

### Disposition
See disposition for theme: "Where confidential apps can run"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
See #1 for proposed disposition
