### ISSUE TITLE
Ballot#71 Hans Buitendijk | The current link to capability statement on http://www.hl7.org/fhir/smart-app-launch/index.html#ehr-launch-sequence lin...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#76]
### Ballot Weight
NEG Clarification

### Where
:: http://www.hl7.org/fhir/smart-app-launch/index.html

### What
Hans Buitendijk
Comment: The current link to capability statement on http://www.hl7.org/fhir/smart-app-launch/index.html#ehr-launch-sequence links to the unversioned fhir page - is that intentional? Or should that point to the STU 3 endpoint? If it's intentional, there should be a blurb about checking the version of FHIR exposed in metadata?
Summary: (minor/typo?) Link to capability statement should be versioned?

### Josh's Triage Notes
Agreed -- need to decide which of these two options is best.

### Disposition
Dispoaition: Persuasive with mod

We can't find this particular link -- but in general, we will want add text explaining that the SMART App Launch spec applies to multiple versions of the FHIR specification. We should include text explaining ""When using this spec with FHIR DSTU2, the CapabilityStatement is instead called ConformanceStatement.""

When the SMART App Launch spec is published in draft/""current"" form, it will link to hl7.org/fhir/*. When the SMART App Launch spec is published in a frozen/""finalized"" form, it will link to hl7.org/fhir/stu3 (or whatever version of FHIR is the most recent when finalization happens).

clarify that we'll still mention DSTU2 + STU3, in addition to any links,

Moved: Eric Haas / Second Isaac Vetter.
9-0-0

### Vote Details
Pro-Con-Abstain: 9-0-0
Date: 2017-11-30

**Comment by Healthedata1** [comment]
partially applied using the[ "publish-box"](https://healthedata1.github.io/smart-app-launch-viewer/) to define which version of FHIR to which the specification applies.
