### ISSUE TITLE
Ballot#72 Hans Buitendijk | The current spec states that launch URL is required (http://www.hl7.org/fhir/smart-app-launch/index.html#registering-a-...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#77]
### Ballot Weight
NEG Clarification

### Where
:: http://www.hl7.org/fhir/smart-app-launch/index.html

### What
Hans Buitendijk
Comment: The current spec states that launch URL is required (http://www.hl7.org/fhir/smart-app-launch/index.html#registering-a-smart-app-with-an-ehr), but in the standalone launch sequence, there is no use of that URL. It should only be required for apps that support being launched in context.
Summary: Why is launch URL required for apps that "launch" outside of the EHR?

### Josh's Triage Notes
Disposition: Persuasive 

We agree to change "one or more" to "zero or more" to indicate that some apps do not need a launch URL. (Specifically: apps that do not use the EHR Launch Flow do not need a launch URL.)

### Disposition
Disposition: Persuasive 

We agree to change "one or more" to "zero or more" to indicate that some apps do not need a launch URL. (Specifically: apps that do not use the EHR Launch Flow do not need a launch URL.)

### Vote Details
Pro-Con-Abstain: 4-0-2
Date: 2017-11-02

**Comment by Healthedata1** [comment]
applied with #240
