### ISSUE TITLE
Ballot#3 Alexander MENSE, HL7 Austria | From: offline access | Guess this means that in case of a web application the server side client has still ...

### ISSUE THREAD

**Issue by jmandel** [HL7/smart-app-launch#8]
### Ballot Weight
A-S Clarification

### Where
Scopes for requesting a refresh token :: smart-app-launch

### What
Alexander MENSE, HL7 Austria
From: offline access
Comment: Guess this means that in case of a web application the server side client has still access even when the front end session for the user has ended â¦ this might not be obvious for everybody, therefore a short clarification would be good.

### Josh's Triage Notes
Merge with theme: "offline_access"

### Disposition
See dispositoin for "Theme: offline_access"

### Vote Details
Pro-Con-Abstain: 
Date:

**Comment by Healthedata1** [comment]
Ballot "offline_access" theme (Ballot#3, Ballot#63, Ballot#74, Ballot#119, Ballot#202)

The specification includes an "offline_access" scope to convey that long-term refresh tokens should be granted. Several comments asked for clarifciations including removal of the recommendation that refresh tokens should expire after 24 hours; and discussion of whether offline_access should be reserved for confidential clients.

[Themes spreadsheet:](https://docs.google.com/spreadsheets/d/1LgfmqZLcEiprCDXrHCG9NyT4rG0wulN0gnwtd4wK1u8/edit#gid=2062261357)
